import { useEffect, useState } from 'react';
import { Linking, StyleSheet, Text, View } from 'react-native';
import { AppShell } from '@/components/app-shell';
import { Card, PrimaryButton, uiStyles } from '@/components/ui';
import { useAppData } from '@/data/app-data';
import { adaptiveReading } from '@/ai/openai-compatible';
import { loadJapaneseNews, NewsArticle } from '@/domain/news';
import { colors, radius, spacing } from '@/design/tokens';
import { FuriganaText } from '@/components/furigana-text';

type Reading = Awaited<ReturnType<typeof adaptiveReading>>;

export default function ReadScreen() {
  const { addItem, connection, profile } = useAppData(); const [topic, setTopic] = useState('Daily life'); const [articles, setArticles] = useState<NewsArticle[]>([]); const [articleIndex, setArticleIndex] = useState(0); const [reading, setReading] = useState<Reading | null>(null); const [status, setStatus] = useState('Loading current Japanese news…'); const [saved, setSaved] = useState(false);
  useEffect(() => { void loadJapaneseNews().then((next) => { setArticles(next); setStatus(next.length ? 'Choose a headline, then ask Sensei to adapt it.' : 'No news items were returned.'); }).catch(() => setStatus('News could not be loaded on this connection. Try again later.')); }, []);
  const article = articles[articleIndex]; const level = profile?.startingComfort ?? 'new to Japanese';
  const generate = async () => { if (!article) return; if (!connection || connection.token.includes('FillYour')) return setStatus('Set up a text AI connection in Settings to adapt this news item.'); setSaved(false); setStatus('Sensei is adapting this headline to your level…'); try { setReading(await adaptiveReading(connection, { headline: article.title, summary: article.summary, topic, supportLanguage: profile?.supportLanguage ?? 'en-US', level })); setStatus('Original practice reading created from the selected headline.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Sensei could not create a reading.'); } };
  const save = async () => { if (!reading || saved) return; await addItem({ kind: 'phrase', japanese: reading.phrase, reading: reading.phraseReading, meaning: reading.phraseMeaning, notes: article ? `Adapted from ${article.source}: ${article.title}` : 'From a Sensei reading.', state: 'seen' }); setSaved(true); };
  const rotate = () => { if (articles.length) { setArticleIndex((articleIndex + 1) % articles.length); setReading(null); setSaved(false); setStatus('Headline selected. Ask Sensei to adapt it.'); } };
  return <AppShell title="Read" subtitle="Current Japanese news, made approachable by Sensei."><Card><Text style={uiStyles.japanese}>Today’s source</Text>{article ? <><Text style={styles.source}>{article.source}</Text><Text style={styles.headline}>{article.title}</Text>{article.summary ? <Text style={uiStyles.muted}>{article.summary}</Text> : null}<View style={styles.topics}>{['Daily life','Travel','Food','Surprise me'].map((name) => <Text accessibilityRole="button" key={name} onPress={() => setTopic(name)} style={[styles.topic, name === topic && styles.selected]}>{name}</Text>)}</View><PrimaryButton label="Ask Sensei to adapt this news" onPress={() => void generate()}/><Text accessibilityRole="link" onPress={() => void Linking.openURL(article.url)} style={styles.link}>Read the original at NHK NEWS WEB</Text><Text accessibilityRole="button" onPress={rotate} style={styles.link}>Choose another headline</Text></> : <Text style={uiStyles.muted}>{status}</Text>}</Card>{reading ? <Card><Text style={styles.title}>{reading.title}</Text><FuriganaText japanese={reading.japanese} reading={reading.reading} showReading={profile?.furiganaMode !== 'none'}/><Text style={uiStyles.body}>{reading.meaning}</Text><PrimaryButton label={saved ? 'Phrase saved' : 'Save a useful phrase'} onPress={() => void save()} /></Card> : null}{status ? <Text style={uiStyles.muted}>{status}</Text> : null}<Text style={uiStyles.muted}>Headlines are loaded from NHK NEWS WEB. Sensei writes original practice reading instead of reproducing the article.</Text></AppShell>;
}
const styles=StyleSheet.create({topics:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},topic:{backgroundColor:colors.surfaceMuted,borderRadius:radius.pill,color:colors.text,fontSize:14,paddingHorizontal:spacing.md,paddingVertical:spacing.sm},selected:{backgroundColor:colors.primary,color:colors.primaryText},source:{color:colors.primary,fontSize:13,fontWeight:'700'},headline:{color:colors.text,fontSize:20,fontWeight:'700',lineHeight:28},title:{color:colors.primary,fontSize:18,fontWeight:'700'},link:{color:colors.primary,fontSize:15,fontWeight:'700'}});
