import { useState } from 'react';
import { StyleSheet, Text, TextInput } from 'react-native';
import { useRouter } from 'expo-router';
import { AppShell } from '@/components/app-shell';
import { Card, PrimaryButton, uiStyles } from '@/components/ui';
import { useAppData } from '@/data/app-data';
import { testConnection, testImageConnection } from '@/ai/openai-compatible';
import { colors, spacing } from '@/design/tokens';

export default function Settings() {
  const { connection, saveConnection } = useAppData(); const router = useRouter(); const [endpoint, setEndpoint] = useState(connection?.endpoint ?? 'https://api.openai.com/v1'); const [model, setModel] = useState(connection?.model ?? ''); const [token, setToken] = useState(connection?.token ?? 'sk-FillYourOpenAITokenHere'); const [separateImageProvider, setSeparateImageProvider] = useState(connection?.separateImageProvider ?? false); const [imageEndpoint, setImageEndpoint] = useState(connection?.imageEndpoint ?? 'https://api.xiaomimimo.com/v1'); const [imageModel, setImageModel] = useState(connection?.imageModel ?? 'mimo-v2.5'); const [imageToken, setImageToken] = useState(connection?.imageToken ?? ''); const [status, setStatus] = useState('');
  const profile = { endpoint, model, token, protocol: 'openai-compatible' as const, separateImageProvider, imageEndpoint, imageModel, imageToken };
  const test = async () => { setStatus('Testing connection…'); const result = await testConnection(profile); setStatus(result.message); };
  const save = async () => { await saveConnection(profile); setStatus('Connection saved on this device.'); };
  const testImage = async () => { setStatus('Testing image connection…'); const result = await testImageConnection(profile); setStatus(result.message); };
  return <AppShell title="Settings" subtitle="Choose how Sensei connects to AI."><Card><Text style={uiStyles.japanese}>Text AI connection</Text><Text style={uiStyles.muted}>Use an OpenAI-compatible endpoint. Your token stays on this device and is excluded from exports.</Text><Field label="Endpoint" value={endpoint} onChangeText={setEndpoint}/><Field label="Model" value={model} onChangeText={setModel} placeholder="model name"/><Field label="Token" value={token} onChangeText={setToken} secureTextEntry/><Text accessibilityRole="checkbox" accessibilityState={{ checked: separateImageProvider }} onPress={() => setSeparateImageProvider(!separateImageProvider)} style={styles.checkbox}>{separateImageProvider ? '☑' : '☐'} Use another AI connection for image analysis</Text>{separateImageProvider ? <><Text style={uiStyles.japanese}>Image AI connection</Text><Field label="Image endpoint" value={imageEndpoint} onChangeText={setImageEndpoint}/><Field label="Image model" value={imageModel} onChangeText={setImageModel}/><Field label="Image token" value={imageToken} onChangeText={setImageToken} secureTextEntry/><PrimaryButton label="Test image connection" onPress={() => void testImage()}/></> : null}<PrimaryButton label="Save connection" onPress={() => void save()}/><PrimaryButton label="Test text connection" onPress={() => void test()}/><Text accessibilityRole="button" onPress={() => router.back()} style={styles.back}>Back without changing screens</Text>{status ? <Text style={styles.status}>{status}</Text> : null}</Card></AppShell>;
}
function Field(props: { label: string; value: string; onChangeText: (v:string)=>void; placeholder?: string; secureTextEntry?: boolean }) { return <><Text style={styles.label}>{props.label}</Text><TextInput {...props} accessibilityLabel={props.label} placeholderTextColor={colors.mutedText} style={styles.input}/></>; }
const styles=StyleSheet.create({label:{color:colors.text,fontSize:14,fontWeight:'700',marginTop:spacing.sm},input:{borderColor:colors.border,borderRadius:10,borderWidth:1,color:colors.text,minHeight:46,paddingHorizontal:spacing.sm},status:{color:colors.primary,fontSize:14,fontWeight:'600'},checkbox:{color:colors.text,fontSize:16,fontWeight:'700',marginTop:spacing.md},back:{color:colors.primary,fontSize:15,fontWeight:'700',textAlign:'center'}});
